print("Please input Foundation English score :")
eng_score = float(input())
print("Please input General Business score :")
biz_score = float(input())
print("Please input Introduction to Computer Systems score :")
comsys_score = float(input())
print("Please input Computer Programming score :")
programming_score = float(input())

print("--- Your Score ---")
print(f"Foundation English : คะแนนที่ได้ {eng_score}")
print(f"General Business : คะแนนที่ได้ {biz_score}")
print(f"Introduction to Computer Systems : คะแนนที่ได้ {comsys_score}")
print(f"Computer Programming : คะแนนที่ได้ {programming_score}")